import type { Metadata } from 'next'
import localFont from 'next/font/local'
import './globals.css'
import { CssBaseline, Container } from '@mui/material'
import Provider from './providers'

import Header from './header/header'
import authenticated from './auth/actions/authenticated'
import logout from './auth/logout'

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
})
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const isAuthenticated = await authenticated()

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Provider authenticated={isAuthenticated}>
          <CssBaseline />
          <Header logout={logout} />
          <Container className={isAuthenticated ? 'mt-10' : ''}>{children}</Container>
        </Provider>
      </body>
    </html>
  )
}
